### ISSUE TITLE
The bot miscalculates the number of searches, resulting in not being able to earn all points

### ISSUE THREAD

**Issue by kaishi961125** [Prem-ium/BingRewards#56]
![image](https://user-images.githubusercontent.com/81787436/219553783-90cab7af-9535-4f56-bdda-4ea2a1eb61b7.png)
![image](https://user-images.githubusercontent.com/81787436/219554635-cb6ed64b-2f35-488c-bcbd-0549004a2a77.png)

**Comment by kaishi961125** [comment]
pc  searches  18*3=54
Mobile  searches 12*3=36

Here are the credits when the bot completes the search

![image](https://user-images.githubusercontent.com/81787436/219554952-420b73ac-c6b1-4887-bbc8-6dce67ca85f0.png)
![image](https://user-images.githubusercontent.com/81787436/219555260-1a822d7a-4ae0-47c7-87f9-de6b58883b46.png)

**Comment by kaishi961125** [comment]
![image](https://user-images.githubusercontent.com/81787436/219592024-cd60b4cf-b5d7-4581-b74b-4bac4f011404.png)
Here the formula calculation error is modified to /3

**Comment by ItzMeDiego** [comment]
so just change it to /3

**Comment by ItzMeDiego** [comment]
in my case i have done Pcsearch=pcsearch+20 for be sure about the completion of all searches

**Comment by Prem-ium** [comment]
You are having this issue because this repository was designed for United States users where 5 points are rewarded per search. In a couple of hours, I will be posting an update which will allow international users to adjust the amount per search using an env variable named `POINTS_PER_SEARCH`

In your case, you will set the variable equal to 3.
