### ISSUE TITLE
Dear Prem-ium,I wonder if this beautiful program can run on mobile

### ISSUE THREAD

**Issue by darewolf-cyber** [Prem-ium/BingRewards#66]
Dear Prem-ium,I wonder if this beautiful program can run on mobile

**Comment by abhaytomar05** [comment]
It is possible, we can rum this script in GitHub codespace on the website on mobile by which we earn more coins whether you have pc or not. It runs on linux on the azure's server. You have to install a browser in that linux also, you can do that by command. I did it on my pc to just reduce the usage of my personal pc.

I don't know, it will really work on Android environment or not.
But it can work either by modifications or without, because there are some apps which provides environment to run python. So, we can do.
